name: Run all tests

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
        database: ['pgsql', 'mariadb']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pgsql, mysqli
          tools: phpunit

      - name: Ensure PHP is in PATH
        run: echo "PHP PATH:$(which php)"
        
      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8

      - name: Install moodle-plugin-ci
        run: |
          export NODE_VERSION=$(node -v)
          export NPM_VERSION=$(npm -v)
          echo "Using Node.js version: $NODE_VERSION and npm version: $NPM_VERSION"
          moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: 'MOODLE_310_STABLE'
          PATH: $PATH:/home/runner/.nvm/versions/node/$(node -v)/bin

      - name: Run phplint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: Run phpcpd
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd || true

      - name: Run phpmd
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Run codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker

      - name: Run validate
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Run savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Run mustache
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Run grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt

      - name: Run phpdoc
        if: ${{ always() }}
        run: moodle-plugin-ci phpdoc

      - name: Run phpunit
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit
